language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - jruby-19mode
  - jruby-9.0.0.0.pre1
script: bundle exec rspec
cache: bundler
